# Lines beginning with # are comments.

[listen]
port = 8900
address =

[jpip]
image_directory = ${ESAJPIP_IMAGE_DIRECTORY}
chunk_size = 64000

[connections]
limit = 128
initial_timeout = 3
timeout = 60

[channels]
limit = 256

[logging]
directory = ${ESAJPIP_LOG_DIRECTORY}
file_enabled = ${ESAJPIP_FILE_LOGGING}
requests = false
