FROM debian:13

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    clang \
    cmake \
    libclang-rt-dev \
    libglib2.0-dev \
    libllhttp-dev \
    libuv1-dev \
    llvm \
    pkg-config \
    python3 \
    valgrind \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
