if(Python3_Interpreter_FOUND)
    file(GLOB_RECURSE ESAJPIP_FUZZ_CORPUS_INPUTS CONFIGURE_DEPENDS
        ${PROJECT_SOURCE_DIR}/tests/vectors/j2k/*.jp2
        ${PROJECT_SOURCE_DIR}/tests/vectors/j2k/*.jpx
        ${PROJECT_SOURCE_DIR}/tests/transcode/fixtures/input/*.jp2
        ${PROJECT_SOURCE_DIR}/tests/merge/fixtures/input/*.jp2)
    add_custom_command(
        OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/corpus.stamp
        COMMAND ${Python3_EXECUTABLE}
                ${CMAKE_CURRENT_SOURCE_DIR}/make_corpus.py
                ${PROJECT_SOURCE_DIR}
                ${ESAJPIP_FUZZ_CORPUS_DIR}
        COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_CURRENT_BINARY_DIR}/corpus.stamp
        DEPENDS
            ${CMAKE_CURRENT_SOURCE_DIR}/make_corpus.py
            ${ESAJPIP_FUZZ_CORPUS_INPUTS})
    add_custom_target(fuzz_corpus DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/corpus.stamp)
else()
    message(WARNING "Python3 not found: fuzz corpus replay tests will not be registered")
endif()

# asn1_pdus.h, for fuzz_asn1: PDU(T) for every type with a T_ACN_Decode in
# the generated headers, in the order of the headers' names and then of
# their declarations. make_corpus.py counts the same declarations for its
# type selectors. Written only when the list changes.
file(GLOB ESAJPIP_ASN1_HEADERS CONFIGURE_DEPENDS ${PROJECT_SOURCE_DIR}/jpeg2000/generated/*.h)
list(SORT ESAJPIP_ASN1_HEADERS)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${ESAJPIP_ASN1_HEADERS})
set(ESAJPIP_ASN1_PDUS "/* Generated by tests/fuzz/corpus.cmake from jpeg2000/generated. */\n")
foreach(header ${ESAJPIP_ASN1_HEADERS})
    file(STRINGS ${header} declarations REGEX "^flag [A-Za-z0-9_]+_ACN_Decode\\(")
    foreach(declaration ${declarations})
        string(REGEX REPLACE "^flag ([A-Za-z0-9_]+)_ACN_Decode\\(.*" "\\1" type "${declaration}")
        string(APPEND ESAJPIP_ASN1_PDUS "PDU(${type})\n")
    endforeach()
endforeach()
file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/asn1_pdus.h.new "${ESAJPIP_ASN1_PDUS}")
configure_file(${CMAKE_CURRENT_BINARY_DIR}/asn1_pdus.h.new
    ${CMAKE_CURRENT_BINARY_DIR}/asn1_pdus.h COPYONLY)

# Generate real responses independently of the Python format/vector corpus.
add_executable(client_fuzz_seeds client_seeds.cc)
esajpip_configure_target(client_fuzz_seeds)
esajpip_client_response_fixtures(client_fuzz_seeds)
target_link_libraries(client_fuzz_seeds PRIVATE esajpip_client jpip)
add_custom_command(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/client-corpus.stamp
    COMMAND ${CMAKE_COMMAND} -E make_directory
        ${ESAJPIP_FUZZ_CORPUS_DIR}/client-response ${ESAJPIP_FUZZ_CORPUS_DIR}/client-source
    COMMAND client_fuzz_seeds
        ${ESAJPIP_FUZZ_CORPUS_DIR}/client-response ${ESAJPIP_FUZZ_CORPUS_DIR}/client-source
    COMMAND ${CMAKE_COMMAND} -E touch ${CMAKE_CURRENT_BINARY_DIR}/client-corpus.stamp
    DEPENDS client_fuzz_seeds ${ESAJPIP_CLIENT_FIXTURES})
add_custom_target(client_fuzz_corpus DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/client-corpus.stamp)
