# Lines beginning with # are comments.

[listen]
port = ${SWHV_PORT_JPIP}
address =

[jpip]
image_directory = ${SWHV_DIR_IMAGE}
chunk_size = 64000

[connections]
initial_timeout = 3
timeout = 60
limit = 500

[logging]
directory = ${SWHV_DIR_LOG}
file_enabled = 1
requests = 0
