//
// Common part for all hardcoded config-*.h files.
// config.h is autogenerated by either autotools or CMake.
// config-*.h files are legacy files, kept for backward compatibility.
//

#ifndef LOG4CPP_CONFIG_PROJECT_COMMON_H
#define LOG4CPP_CONFIG_PROJECT_COMMON_H

/* Name of package */
#ifndef LOG4CPP_PACKAGE
#define LOG4CPP_PACKAGE "log4cpp"
#endif

/* Define to the full name of this package. */
#ifndef LOG4CPP_PACKAGE_NAME
#define LOG4CPP_PACKAGE_NAME "log4cpp"
#endif

/* Define to the full name and version of this package. */
#ifndef LOG4CPP_PACKAGE_STRING
#define LOG4CPP_PACKAGE_STRING "log4cpp 1.1.6"
#endif

/* Define to the one symbol short name of this package. */
#ifndef LOG4CPP_PACKAGE_TARNAME
#define LOG4CPP_PACKAGE_TARNAME "log4cpp"
#endif

/* Define to the home page for this package. */
#ifndef LOG4CPP_PACKAGE_URL
#define LOG4CPP_PACKAGE_URL "https://log4cpp.sourceforge.net"
#endif

/* Define to the version of this package. */
#ifndef LOG4CPP_PACKAGE_VERSION
#define LOG4CPP_PACKAGE_VERSION "1.1.6"
#endif

/* Version number of package */
#ifndef LOG4CPP_VERSION
#define LOG4CPP_VERSION  "1.1.6"
#endif

#endif // LOG4CPP_CONFIG_PROJECT_COMMON_H
